[context.production.environment]
  HUGO_VERSION = "0.19"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.19"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.19"