[build]
  publish = "public"
  command = "./build.sh"

[context.production.environment]
  HUGO_VERSION = "0.30"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.30"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.30"